apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: jvm-build-suite-component-xaau
  namespace: jvm-build-lsch-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/test-images@sha256:36c42cbade03c7e43ef14e792f7b5be1263415f257e6e6a6b6cf294248e81faf
        name: container-image
        resources: {}
status: {}
